version: '3'
services:
#mssql docker
  pickmeup-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - pickmeupnet2023

  pickmeup-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:Server=pickmeup-sql,1433;Database=PickMeUp;User=sa;Password=QWElkj132;ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7198:7198
    networks:
      - pickmeupnet2023
    links:
      - pickmeup-sql
    depends_on:
      - pickmeup-sql
      
networks:
  pickmeupnet2023:
    driver: bridge      